services:
  glpi-db:
    extends:
      file: GLPI/glpi.yml
      service: glpi-db
  glpi:
    extends:
      file: GLPI/glpi.yml
      service: glpi

  zabbix-db:
    extends:
      file: Zabbix/zabbix.yml
      service: zabbix-db
  zabbix-server:
    extends:
      file: Zabbix/zabbix.yml
      service: zabbix-server
  zabbix-web:
    extends:
      file: Zabbix/zabbix.yml
      service: zabbix-web

  grafana:
    extends:
      file: Grafana/grafana.yml
      service: grafana

  backup-monitoramento:
    extends:
      file: backup/backup.yml
      service: backup-monitoramento

networks:
  itsm_shared_net:
    external: true
