apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    isDefault: true
    url: http://zabbix-web:8080/api_jsonrpc.php
    jsonData:
      username: Admin
      trends: true
      cacheTTL: 300
      timeout: 60
    secureJsonData:
      password: zabbix
    basicAuth: false
    editable: true