services:
  # 1. Grafana (Visualização)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "127.0.0.1:13000:3000" # Acesso ao Grafana (bind local)
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - itsm_shared_net
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  grafana_data:

networks:
  itsm_shared_net:
    external: true
